name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            libxrandr-dev \
            libxcursor-dev \
            libudev-dev \
            libopenal-dev \
            libflac-dev \
            libvorbis-dev \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            libdrm-dev \
            libgbm-dev

      - name: Install Conan
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install conan

      - name: Setup Conan profile
        run: conan profile detect --force

      - name: Install dependencies with Conan
        run: |
          conan install . --build=missing

      # Build the project
      - name: Build project
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
