name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-tidy

      # Run linting
      - name: Run lint checks
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh
