name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-tidy

      - name: Install Conan
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install conan

      - name: Setup Conan profile
        run: conan profile detect --force

      - name: Install dependencies with Conan
        run: |
          conan install . --build=missing

      # Run linting
      - name: Run lint checks
        run: |
          chmod +x ./scripts/lint.sh
          ./scripts/lint.sh
